### PR TITLE
feat(DarkMode): Add dark mode to the ThemeProvider

### LINKED ISSUE #297: Add dark mode to the theme
Add dark mode to the theme to make our apps even greater!

### PR DESCRIPTION
**Pull request by bertearazvan**
## This PR

Closes #297 

## Notes

- It adds the dark mode colors
- It adds the `greys` array as part of the theme which should be the preferred way of colors this way forward.
- It accommodates being reverse-compatible with the lightGrey, mediumGrey and darkGrey.
- It adds a new prop as part of the theme Provider that defaults to 'light' so other apps that might have colors that break due to being "custom" and not properly taken from the theme.

### Fulfilled the scope of this repo?

- [x] The same functionality of the component can not be achieved with theming, basic styling or composition of existing components
- [x] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

### Completness

- ~~[ ] Story included~~ - maintaining a story with the themeProvider I think is redundant and we should find a better way to achieve this.

### CODE REVIEW

**Comment by bertearazvan** [comment]
@rosudhi @goneale @rasa2k @nfour 

Hey amazing devs. Here is the developed theme provider with a dark mode feature. I think it's pretty neat and I tested it out in my local projects, and it works great WITHOUT hardcoded colors on the project level. _The colors should only be taken from the theme._

If you are up for a review, feel free to provide one without being asked. If no review is provided I will merge this on **Friday the 13th** based on my review and tests.

**Comment by bertearazvan** [comment]
99598964c001b9ec06ecbbe99845bc00
e4f95edae94cb576ac52e75dd42e75de
443549119245e78f543de2f0b25d3961

**Comment by rasa2k** [comment]
It looks awesome @bertearazvan

**Comment by rasa2k** [comment]
I've reviewed your dark theme PR and overall it looks good.
I see that you have cleaned up some old color definitions which is good, but is it than backwards compatible.-?

**Pull request merged**
