### PR TITLE
Feature/msalprovider

### PR DESCRIPTION
**Pull request by rasa2k**

### CODE REVIEW

**Comment by bertearazvan** [comment]
Hi @rasa2k please export your component as part of the `index.ts` file so that it can be imported as `import { Component } from "@dhi/react-components-lab"`

**Comment by rasa2k** [comment]
> Hi @rasa2k please export your component as part of the `index.ts` file so that it can be imported as `import { Component } from "@dhi/react-components-lab"`

Hi @bertearazvan,
I would do that if the wrapper could be used as a component, but it can't. So I don't see the need or am I misunderstanding you.?

**Comment by bertearazvan** [comment]
Based on what we discuseed:
- Let's try and make this an actual Provider that can be shared. We would pass properties to this Provider and we would wrap our apps with it and it would work. - Similar to the ThemeProvider to which we pass a theme instance.
- If the above doesn't work, we will try and make it an example of how to use Domain Services with msal, which could live in a story with nice code snippets and so on.

I will convert this to a draft PR instead - because it will be a work in progress for a bit of time.

**Comment by bertearazvan** [comment]
Hi @rasa2k, is there any update about this?

**Comment by rasa2k** [comment]
> 

Hi Razvan,
Nope, there is no update.

**Comment by bertearazvan** [comment]
As this is not in progress anymore I would like to close this PR. You can feel free to reopen it if you plan to work on it.

**Pull request closed without merging**
