### PR TITLE
Speed up pipeline. Try out different options 

### LINKED ISSUE #225: Speed up lab workflow in PRs
Should aim to half the the PR deployment pipeline time

Things to try:
- Set up github actions workflow to cache all package `node_modules` dirs
- Check if installing dependencies for lab package separately is required

### LINKED ISSUE #253: Update repository with yarn 2
Hi all,

We had a few issues in the recent past in regards to the pipeline runs, and how much does a pipeline take to install dependencies, build the app and publish it with azure web apps. 

Initially, the pipeline took around **9-11 minutes** to finish, while in #251 where yarn 2 was implemented, it took around **~5 minutes** (and it can be taken even further). I and @rihr have started using _yarn 2_ for a few months now in our Data 'n Analytics apps, and everything works well, also in production. We find that it behaves well, without any bugs, more performant and a slightly prettier CLI.

In theory, it does not change anything on your end. Everything would be set up already and it will be the same as the good old `yarn install` when working with the `react-components` package. You can read more about the changes here https://medium.com/swlh/getting-started-with-yarn-2-and-typescript-43321a3acdee

So we were wondering, are you good with making this change? 

CC: @goneale @nfour @jharper93 @FranzThomsen1089 @rosudhi

### PR DESCRIPTION
**Pull request by bertearazvan**
## This PR

Closes #225 
Closes #253

In this PR:
- [x] updated to yarn 2 workspaces, removed lerna.
- [x] moved some devDependencies of the packages in the root folder.
- [x] Tried out yarn with pnpm.  `svgr` is failing as it can't find the plugin.
- [x] Adds caching node modules as part of the pipeline flow.
- [x] Pipeline taken from ~10 minutes to ~5 minutes.

### CODE REVIEW

**Comment by bertearazvan** [comment]
Mentioning #225

**Comment by rihr** [comment]
Did the time reduce only because of the yarn 2 change?

with `nodeLinker: node-modules` committing cache isn't worth it.
Could considering caching the cache for the workflow though? https://github.com/actions/cache

**Comment by bertearazvan** [comment]
I was thinking to remove the "nodeLinker: node-modules" and see how it works with the pnp module, and committing the .cache file.

From my understanding @rihr, that caching works only if we would have chaining workflows where "node_modules" is needed, therefore not worth installing twice. 
In our case, I don't think it will work because we have only 1 workflow, so there is something to cache, but nothing to take from cache.

**Comment by bertearazvan** [comment]
I think, before this change it would install the dependencies once before, and once during the app deploy. Now it's happening only once.

**Comment by rihr** [comment]
Doesn't that just state that independent workflow runs often reuse the same downloaded dependencies?

**Comment by bertearazvan** [comment]
Hmm, could be. At least from my experience I know I tried it somewhere and I hit that wall where I had the realization that it doesn't cache on independent jobs on separate "runs" but only if they are part of the same "run".

You can give it a try, it would be cool if it does work, and we would merge this one once we have their approval. I will try and write a gh issue and tag the active members.

**Comment by rihr** [comment]
I didn't get to it, but I think removing the `env: true` param from the install step should work as a temporary workaround to disable frozen lockfile requirement, to see if it's faster

**Comment by bertearazvan** [comment]
@rihr Seems like the pipe has come down to 3m with cache applied. Indeed, seems that cache can be saved between runs :)

**Comment by bertearazvan** [comment]
@rihr I believe this is ready to be merged, but can you review it one more time?

**Comment by bertearazvan** [comment]
@nfour Any thoughts on the above question?

**Comment by nfour** [comment]
> @nfour Any thoughts on the above question?

Without setting things up and replicating it's hard to know, but generally in order for PNPM Workspaces to work right you need everything defined correctly. Meaning it replaces lerna etc. and you define all your peer dependencies, including making dependent projects part of the workspace. If a particular package is having trouble in my experience it's an issue with the package itself resolving things funny.

**Comment by bertearazvan** [comment]
> but generally in order for PNPM Workspaces to work right you need everything defined correctly. 

I saw that it is pretty restrictive in that sense. I would make it an improvement of the current setup, and if time allows you can have a look since you have more experience with it 🥇

**Pull request merged**
