### PR TITLE
Feature/timeseries calendar

### PR DESCRIPTION
**Pull request by bertearazvan**
## This PR

Adds the components needed for creating calendars.

## Submission criteria

Please review the below criteria before asking for a review.

### Fulfilled the scope of this repo?

- [x] The same functionality of the component can not be achieved with theming, basic styling, or composition of existing components
- [x] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

### Completness

- [x] Story included

### CODE REVIEW

**Comment by bertearazvan** [comment]
@rihr there is a weird linting error about the dependency cycle which I can't really spot why. There isn't anything different then for example the `GapBox` component

**Comment by bertearazvan** [comment]
Removed the step for installing the dependencies on the package level for the lab #225

**Review by rihr — APPROVED** [review]
Looks good :+1: 

I seem to remember we already tried removing the install step for lab before, but for whatever reason it was required

**Comment by bertearazvan** [comment]
> Looks good 👍
> 
> I seem to remember we already tried removing the install step for lab before, but for whatever reason it was required

The step is removed and the pipe has passed. Although, I don't see a huge improvement in execution time. I can certainly see that the build and deploy part takes 5 minutes, which is a lot. At least we checked something on that list ✅ #225

**Pull request merged**
