### PR TITLE
Feature/staging prs

### LINKED ISSUE #97: Staging deployments for PRs?
When reviewing a PR when a component gets added to the lab, it would be useful to see a staging deployment with how the component looks in the storybook. At the same time, it would help in the case of storybook UI enhancements. 

At the moment, the static-web-app(preview) resource is taking care of that out of the box. Are there other Azure resources having this feature that might not be in the "preview" stage?

This feature will require some pipeline work to only deploy stuff related to the react-components-lab.

@elbys @rihr @j08lue @rosudhi

### PR DESCRIPTION
**Pull request by bertearazvan**
## This PR

Closes #97

### CODE REVIEW

**Comment by j08lue** [comment]
Azure Static Web Apps: Your stage site is ready! Visit it here: https://green-glacier-08aae7903-147.westeurope.azurestaticapps.net

**Comment by j08lue** [comment]
Azure Static Web Apps: Your stage site is ready! Visit it here: https://green-glacier-08aae7903-147.westeurope.azurestaticapps.net

**Review by rihr — COMMENTED** [review]
Why aren't the deploy comments from the github-bot? 

As far as I know, if you leave
```
repo_token: ${{ secrets.GITHUB_TOKEN }}
```
as default, without declaring the GITHUB_TOKEN secret, it will just use a default repo-scoped token and post with the bot

**Comment by bertearazvan** [comment]
> as default, without declaring the GITHUB_TOKEN secret, it will just use a default repo-scoped token and post with the bot

I had to make this pipeline setup more manually than usual because I am not an Owner of the @DHI organization, let's see if that works, it'd be cool :D

**Comment by j08lue** [comment]
Azure Static Web Apps: Your stage site is ready! Visit it here: https://green-glacier-08aae7903-147.westeurope.azurestaticapps.net

**Comment by bertearazvan** [comment]
> Azure Static Web Apps: Your stage site is ready! Visit it here: https://green-glacier-08aae7903-147.westeurope.azurestaticapps.net

@rihr This one wasn't from the last commit :)

**Pull request merged**
