### PR TITLE
add Switch to Theme Story

### LINKED ISSUE #120: Add basic components to the ThemeProvider Story
It would be very useful to see how do the normal components `Button, Switch, Input etc.` look with the theme applied.

We should group them based on their category so it looks visually appealing and structured.

### PR DESCRIPTION
**Pull request by bertearazvan**
## This PR

Closes #120 

This PR aims to add all the relevant components that the ThemeProvider implements. Ideally, it should prove how the basic components look by being styled through the theme.

Let's all contribute to this PR and add components from MaterialUI. 
I believe we should find a good structure for them as well, looking for proposals 👍🏼

### CODE REVIEW

**Comment by rosudhi** [comment]
looking good. I will make design mockup for component list.

**Comment by rosudhi** [comment]
Here it is.
Untitled

**Comment by bertearazvan** [comment]
Looks quite nice. I think we should think of a way to make adding these components as efficient as possible.

Maybe to generate them based on some json file that contains the instance of that such as
```
{
   title: '',
   description: '',
   components: [
      {
         component: <Comp {...props} />,
         codeExample: '<Button variant='contained' color='primary'>\n{'Primart'}\n</Button>
      }
   ]
}
```

**Comment by rosudhi** [comment]
Cool, exactly same as what i've been thinking. i will implement the mockup.

**Comment by rosudhi** [comment]
I just update this branch with new layout changes, let me know what's your thought about it!. the work still on progress, so i convert it to draft.

**Comment by bertearazvan** [comment]
I updated the layout as well, such that it looks the same as the image you provided. Please give it a try and let me know how it feels. 

I would personally choose to remove the ThemeProvider code example as it feels a bit pointless there and keeps only the components. If anything, for the ThemeProvider we could simply add something like this:
```
<ThemeProvider>
   {children}
</ThemeProvider>
```

moreover, I would make the code example toggle-able which means we could wrap that Syntax in a `Collapse` component and add a button like "Show code" or something.

**Comment by bertearazvan** [comment]
I will add the button for ShowCode

**Comment by rosudhi** [comment]
> I updated the layout as well, such that it looks the same as the image you provided. Please give it a try and let me know how it feels./
> 
> I would personally choose to remove the ThemeProvider code example as it feels a bit pointless there and keeps only the components. If anything, for the ThemeProvider we could simply add something like this:
> 
> ```
> <ThemeProvider>
>    {children}
> </ThemeProvider>
> ```
> 
> moreover, I would make the code example toggle-able which means we could wrap that Syntax in a `Collapse` component and add a button like "Show code" or something.

> I will add the button for ShowCode and change the ThemeProvider code example to be shorter, as suggested above.

yes, hide by default sounds good. sure, i will separate navbar to different component instead, if possible i will make it as a generic component also, i think it's good prospect as a candidate.

more update is coming soon, need to get something done on other project as well.

**Comment by bertearazvan** [comment]
Would it make sense to consider this PR as done?

**Comment by rosudhi** [comment]
> Would it make sense to consider this PR as done?

i don't think so, there still pending work on this PR. it's been hard to managed the time to work on this, these days, but i will do this,  maybe within next couple day(s).

**Comment by bertearazvan** [comment]
No worries time-related, whenever time allows. I was wondering just because I remember we have most of the things needed, and yeah maybe it would make sense to have more components added to the theme, but it feels like the "template" for adding components is good to go. 

Actually, now that I think about it, probably there were some small fixes that were to be done before merging.

**Comment by rosudhi** [comment]
there are at least 2 things left that i would like to be added to this PR:
- colors.
- some ehancement to side nav and bug fix.
last stage my work on this is already around 95% completed. after that, i am pretty confidence to close this PR. i will give some time for today, then.

**Comment by bertearazvan** [comment]
Nice work!

**Pull request merged**
