### PR TITLE
Update Font

### PR DESCRIPTION
**Pull request by JeanLoureiro**
After implementing Job Log detail I realized we have the following warning from React. 

Warning: Cannot update a component (`JobList`) while rendering a different component (`AutoSizer`). `

This is due to the AutoSizer setting the width of the table, we are passing the value to the parent component (JobList) and the state gets updated. 
We need to pass the width up to make the table responsive. I thought of a few ways to fix it, but it won’t work due to how AutoSizer works. 

Also, I could create a hook to control the window height and width and plugin it to JobList, that way I can remove AutoSizer from that table. This will potentially fix the issue. 

However, I talked to @goneale  and we agreed that it would be better to wait for MUI-X and redo the entire table when the time comes.

### CODE REVIEW

**Review by FranzThomsen1089 — APPROVED** [review]
Awesome

**Comment by goneale** [comment]
First thing I did was un-maximise the browser, and this behavior exhibited.

I know we are having trouble with responsiveness, but is this a simple one?

image

**Comment by goneale** [comment]
This table component really is horrible at handling responsiveness. Probably we can't do much about this one either.
image

**Comment by goneale** [comment]
^^ It's not much of a big deal, as it only is affected when Log Detail is open

**Comment by goneale** [comment]
But otherwise it gets the job done, thanks 👏👏

**Comment by JeanLoureiro** [comment]
> This table component really is horrible at handling responsiveness. Probably we can't do much about this one either.
> image

`Terrible :/ maybe we can create a package to deal with this... maybe

**Comment by JeanLoureiro** [comment]
> ^^ It's not much of a big deal, as it only is affected when Log Detail is open

this happens within a couple of pixels before the table starts stretching the columns to make it full width.... this is fixable, but a pain. Don't think we should invest time on it as we are going to be replacing this anyway :)

**Pull request merged**
